sudo: required

addons:
  artifacts:
   # ...
   paths:
     - $(git ls-files -o | grep travis_artifacts | tr "\n" ":")

language: php

php:
  - 5.6

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

services:
  - docker

before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --no-interaction
  - sudo rm /usr/local/bin/docker-compose || true
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose -f docker-compose-ci.yml up -d
  - docker ps -a

script:
  - docker exec -i openfolio_ci_web bash /var/www/scripts/openfolio/check-coding-standards.sh
  - docker exec -i openfolio_ci_web bash /var/www/scripts/openfolio/install/install_script.sh
  - docker exec -i openfolio_ci_web bash /var/www/scripts/openfolio/check-feature-state.sh openfolio
  - docker exec -i openfolio_ci_web_scripts sh /var/www/scripts/openfolio/unit-tests.sh
  - docker exec -it openfolio_ci_behat sh /var/www/scripts/openfolio/behatstability.sh
