version: "2"

services:
  web_scripts:
    image: asghaier/openfolio_docker:ci
    volumes:
     - ./:/var/www
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"
    container_name: openfolio_ci_web_scripts

  web:
    image: asghaier/openfolio_docker:ci
    volumes:
     - ./:/var/www
    links:
     - db:db
     - mailcatcher:mailcatcher
    environment:
     - DRUPAL_SETTINGS=production
    ports:
     - "80"
    network_mode: "bridge"
    container_name: openfolio_ci_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openfolio
    volumes:
     - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"
    container_name: openfolio_ci_db

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.openfolio.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: openfolio_mailcatcher

  selenium:
    image: selenium/standalone-firefox:2.48.2
    links:
     - web:web
    volumes:
      - ./html/profiles/contrib/openfolio/tests/behat/features/files/:/files
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: openfolio_ci_selenium

  behat:
    image: asghaier/openfolio_docker:ci
    volumes:
     - ./:/var/www
    links:
     - web:web
     - db:db
     - selenium:selenium
     - mailcatcher:mailcatcher
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"
    container_name: openfolio_ci_behat

volumes:
  db_data:
