version: "2"

services:
  web:
    image: asghaier/openfolio_docker:dev
    volumes:
     - ./:/var/www
    links:
     - db
     - mailcatcher
    environment:
     - VIRTUAL_HOST=openfolio.dev
     - DRUPAL_SETTINGS=development
    ports:
     - "80"
    network_mode: "bridge"
    container_name: openfolio_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openfolio
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"
    container_name: openfolio_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.openfolio.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: openfolio_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/openfolio/tests/behat/features/files/:/files
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: openfolio_selenium

  behat:
    image: asghaier/openfolio_docker:dev
    volumes:
     - ./:/var/www
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: openfolio_behat

  cron:
    image: asghaier/openfolio_docker:cron
    volumes:
     - ./:/var/www
    links:
     - db
     - mailcatcher
    environment:
     - DRUPAL_SETTINGS=development
    network_mode: "bridge"
    container_name: openfolio_cron

volumes:
  db_data:
